# Check out https://docs.codemagic.io/getting-started/building-a-react-native-app/ for more information
# Please review and update values in curly braces

workflows:
    react-native:
        name: React Native App
        environment:
            node: latest
        triggering:
            events:
                - push
                - tag
                - pull_request
            branch_patterns:
                - pattern : master
                  include: true
                  source: true
        scripts:
            - npm install
            - echo "sdk.dir=$HOME/programs/android-sdk-macosx" > "$FCI_BUILD_DIR/android/local.properties"
            - |
                # build Android
                cd android
                ./gradlew assembleRelease
        artifacts:
            - android/app/build/outputs/**/*.apk
    ios-workflow:
        name: iOS Workflow
        max_build_duration: 60
        environment:
            node: latest
            xcode: latest
            cocoapods: default
        triggering:
            events:
                - push
                - tag
                - pull_request
            branch_patterns:
                - pattern: master
                include: true
                source: true
        scripts:
            - name: Install npm dependencies
            script: npm install
            - name: Install CocoaPods dependencies
            script: |
                cd ios
                pod repo update
                pod install
            - name: Increment build number
            script: cd ios && agvtool new-version -all $(($BUILD_NUMBER +1))
        artifacts:
            - build/ios/ipa/*.ipa
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
        publishing:
            email:
                recipients:
                    - bdevaney'acquisbi.com
